on: push

jobs:
  modelcheck:
    name: Model Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v5
      - run: ./gradlew checkModels --info
